name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'      
      - name: Restore dependencies
        run: dotnet restore MemoryPlaces.sln
      - name: Build the solution
        run: dotnet build MemoryPlaces.sln --no-restore --configuration Release      
      - name: Run tests
        run: dotnet test MemoryPlaces.sln --no-build --configuration Release --verbosity normal      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.xml'
